config/routes.rb
Rails.application.routes.draw do

  root to: "tools#index"
  resources :tools
  resources :users, only: [:new, :create, :show]

  get '/login' to: 'sesssion#new'
  post '/login' to: 'session#create'

end

app/models/tool.rb
class Tool < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessionscontroller.rb
class SessionController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:sessions][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else

    end
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @tools = Tool.all
  end

  def new
    @tool = Tool.new
  end

  def create
    tool = Tool.new(tool_params)
    if tool.save
      redirect_to tools_path
    else
      render :new
    end
  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    tool = Tool.find(params[:id])
    updated = tool.update(tool_params)
    if updated
      redirect_to tools_path
    end
  end

  def destroy
    Tool.delete(params[:id])
    redirect_to tools_path
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :quantity, :price)
  end
end

app/controllers/users_controller.rb
class UserController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else

    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    Welcome <%= current_user.username %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/tools/edit.html.erb
<%= form_for(@tool) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :quantiy %>
  <%= f.number_field :quantity %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>
<% end %>

app/views/tools/index.html.erb
<div class="tool_info">
  <% @tools.each do |tool| %>
  <ul>
    <li><strong>Name:</strong>     <%= tool.name %></li> <br/>
    <li><strong>Price:</strong>    <%= tool.price %></li> <br/>
    <li><strong>Quantity:</strong> <%= tool.quantity %></li> <br/>
    <%= link_to "Edit Tool", edit_tool_path(tool.id) %></li>
    <%= link_to "Delete Tool", tool_path(tool.id), method: :delete %>
  </ul>
      <br/>
<br/>
  <% end %>
</div>

<%= link_to "New Tool!", new_tool_path %>

app/views/tools/new.html.erb
<%= form_for(@tool) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :quantiy %>
  <%= f.number_field :quantity %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Create a new account</h1>

<%= form_for(@user) do |f| %>
<%= f.label :username %>
<%= f.text :username %> <br/>

<%= f.label :password %>
<%= f.text :password %> <br/>
 <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>User show page</h1>